language: rust
jobs:
  include:
    - rust: stable
      os: linux
    - rust: stable
      os: osx
    # - rust: stable
    #   os: windows # windows build currently causes GCC on Travis to ICE.
    - rust: beta
      os: linux
    - rust: nightly
      os: linux
